Repository dwavesystems/dwave-optimization, pull requests merged in 2024-07, with the labels that each got.

#49 Make `maybe_equals` consistently return integers
  dwave/optimization/model.pyx
  dwave/optimization/symbols.pyx
  releasenotes/notes/maybe_equals-return-type-dd06bd6f8b2f31f3.yaml
  tests/test_symbols.py
Labels: bug, documentation

#55 Improve doc testing
  .circleci/config.yml
  docs/conf.py
  docs/index.rst
  docs/intro.rst
  docs/requirements.txt
  dwave/optimization/model.pyx
  dwave/optimization/symbols.pyx
Labels: bug, documentation

#56 Add model attributes objective states to docs
  docs/reference/models.rst
  dwave/optimization/model.pxd
Labels: documentation, enhancement

#57 Flatten symbols documentation
  docs/reference/symbols.rst
Labels: documentation, enhancement

#61 Construct C++ `NaryOpNode` from `Array*`
  dwave/optimization/include/dwave-optimization/nodes/mathematical.hpp
  dwave/optimization/src/nodes/mathematical.cpp
  releasenotes/notes/NaryOpNode-from-Array-pointers-bdf7c53f9850d9c2.yaml
  tests/cpp/tests/test_nodes_mathematical.cpp
Labels: enhancement

#63 Restructure symbol tests
  tests/test_symbols.py
Labels: enhancement

#68 Improve operator overloading for array symbols
  dwave/optimization/libcpp/nodes.pxd
  dwave/optimization/model.pyi
  dwave/optimization/model.pyx
  dwave/optimization/src/nodes/mathematical.cpp
  dwave/optimization/symbols.pyx
  releasenotes/notes/improve-operators-54e60d66200526cc.yaml
  tests/test_examples.py
  tests/test_model.py
  tests/test_symbols.py
Labels: bug, enhancement

#72 Support `<,>,==,!=,<=,>=,int,bool,not` operations on Constant
  dwave/optimization/symbols.pyi
  dwave/optimization/symbols.pyx
  releasenotes/notes/constant-comparisons-5258fa0aeb7f435e.yaml
  tests/test_symbols.py
Labels: enhancement

#73 Flatten generator docs
  docs/conf.py
  docs/reference/generators.rst
  dwave/optimization/generators.py
Labels: documentation, enhancement
