Repository dwavesystems/dwave-optimization, pull requests merged in 2024-11, with the labels that each got.

#158 Update build requirements in requirements.txt
  requirements.txt
Labels: bug

#161 Add methods to remove unused symbols from a model
  docs/reference/models.rst
  dwave/optimization/include/dwave-optimization/graph.hpp
  dwave/optimization/include/dwave-optimization/nodes/collections.hpp
  dwave/optimization/libcpp/graph.pxd
  dwave/optimization/model.pyi
  dwave/optimization/model.pyx
  dwave/optimization/src/graph.cpp
  releasenotes/notes/feature-remove-unused-symbols-5ad976d5935e417c.yaml
  tests/cpp/test_graph.cpp
  tests/test_model.py
Labels: enhancement

#159 Feature/modulus
  docs/reference/math.rst
  dwave/optimization/include/dwave-optimization/nodes/mathematical.hpp
  dwave/optimization/libcpp/nodes.pxd
  dwave/optimization/mathematical.py
  dwave/optimization/model.pyi
  dwave/optimization/model.pyx
  dwave/optimization/src/nodes/mathematical.cpp
  dwave/optimization/symbols.pyi
  dwave/optimization/symbols.pyx
  releasenotes/notes/add-modulus-9955080919218848.yaml
  tests/cpp/nodes/mathematical/test_binaryop.cpp
  tests/test_symbols.py
Labels: enhancement

#167 Implement `BinaryOpNode::sizeinfo()`
  dwave/optimization/include/dwave-optimization/nodes/mathematical.hpp
  dwave/optimization/src/nodes/mathematical.cpp
  releasenotes/notes/BinaryOpNode-sizeinfo-ac3a01130d77efcc.yaml
  tests/cpp/nodes/mathematical/test_binaryop.cpp
Labels: bug, enhancement

#162 Refactor ArrayIterator for random access and clearer const/non-const
  dwave/optimization/include/dwave-optimization/array.hpp
  dwave/optimization/src/nodes/mathematical.cpp
  releasenotes/notes/iterator-refactor-7c21470cc6a232c9.yaml
  tests/cpp/test_array.cpp
Labels: enhancement

#170 Update README's Contributing section with Release Note subsection
  README.rst
Labels: documentation, enhancement

#169 Adding symbol for sqrt
  dwave/optimization/include/dwave-optimization/nodes/mathematical.hpp
  dwave/optimization/libcpp/nodes.pxd
  dwave/optimization/mathematical.py
  dwave/optimization/model.pyi
  dwave/optimization/src/nodes/mathematical.cpp
  dwave/optimization/symbols.pyi
  dwave/optimization/symbols.pyx
  releasenotes/notes/add-sqrt-node-48c30ba46bb85f55.yaml
  tests/cpp/nodes/mathematical/test_unaryop.cpp
  tests/test_symbols.py
Labels: enhancement

#173 Update version 0.4.2.dev -> 0.4.2
  dwave/optimization/__init__.py
Labels: enhancement

#153 Add `ConcatenateNode`
  docs/reference/math.rst
  dwave/optimization/include/dwave-optimization/nodes/manipulation.hpp
  dwave/optimization/libcpp/nodes.pxd
  dwave/optimization/mathematical.py
  dwave/optimization/src/nodes/_state.hpp
  dwave/optimization/src/nodes/manipulation.cpp
  dwave/optimization/symbols.pyi
  dwave/optimization/symbols.pyx
  tests/cpp/nodes/test_manipulation.cpp
  tests/test_symbols.py
Labels: enhancement
