Repository dwavesystems/dwave-optimization, pull requests merged in 2024-10, with the labels that each got.

#126 Fix `where` docstring in` mathematical.py`
  dwave/optimization/mathematical.py
Labels: bug, documentation

#128 Add CVRPTW generator
  dwave/optimization/generators.py
  releasenotes/notes/add-CVRPTW-generator-9315a2fe767d934a.yaml
  tests/test_generators.py
Labels: enhancement

#89 Feature/disjoint more mutate methods
  dwave/optimization/include/dwave-optimization/nodes/collections.hpp
  dwave/optimization/src/nodes/collections.cpp
  releasenotes/notes/add-disjoint-lists-set-state-method-49cb6ade68a2f2ec.yaml
  tests/cpp/tests/test_nodes_collections.cpp
Labels: enhancement

#123 Use catch2 version 3.7.1
  .circleci/config.yml
  dwave/optimization/include/dwave-optimization/nodes/numbers.hpp
  dwave/optimization/src/nodes/numbers.cpp
  subprojects/catch2.wrap
  tests/cpp/meson.build
  tests/cpp/test_main.cpp
  tests/cpp/tests/test_array.cpp
  tests/cpp/tests/test_examples.cpp
  tests/cpp/tests/test_graph.cpp
  tests/cpp/tests/test_nodes_collections.cpp
  tests/cpp/tests/test_nodes_constants.cpp
  tests/cpp/tests/test_nodes_flow.cpp
  tests/cpp/tests/test_nodes_indexing.cpp
  tests/cpp/tests/test_nodes_mathematical.cpp
  tests/cpp/tests/test_nodes_numbers.cpp
  tests/cpp/tests/test_nodes_quadratic_model.cpp
  tests/cpp/tests/test_utils.cpp
  tests/cpp/tests/utils.hpp
Labels: bug, enhancement

#114 Feature/partial sum
  dwave/optimization/include/dwave-optimization/array.hpp
  dwave/optimization/include/dwave-optimization/nodes/mathematical.hpp
  dwave/optimization/libcpp/nodes.pxd
  dwave/optimization/model.pyi
  dwave/optimization/model.pyx
  dwave/optimization/src/array.cpp
  dwave/optimization/src/nodes/mathematical.cpp
  dwave/optimization/symbols.pyi
  dwave/optimization/symbols.pyx
  releasenotes/notes/partial-sum-node-ca3356c3bddfacde.yaml
  tests/cpp/tests/test_array.cpp
  tests/cpp/tests/test_nodes_mathematical.cpp
  tests/test_symbols.py
Labels: enhancement

#130 Raise better error messages from indexing arrays
  dwave/optimization/libcpp/graph.pxd
  dwave/optimization/model.pyi
  dwave/optimization/src/nodes/indexing.cpp
  dwave/optimization/symbols.pyx
  releasenotes/notes/feature-better-indexing-error-messages-2e2ce0e2bbebb42e.yaml
  tests/test_symbols.py
Labels: enhancement

#131 Allow `dwave.optimization.symbols._register` to be `cimport`-ed
  dwave/optimization/symbols.pxd
  dwave/optimization/symbols.pyx
Labels: enhancement

#132 Add decrement operator for ArrayIterator
  dwave/optimization/include/dwave-optimization/array.hpp
  tests/cpp/tests/test_array.cpp
Labels: enhancement

#134 Bugfix/cvrptw generator
  dwave/optimization/generators.py
  releasenotes/notes/fix-cvrptw-generator-044c7d7b5ad1c112.yaml
  tests/test_generators.py
Labels: bug

#135 FIx typo: value 2 should be 3
  docs/intro.rst
Labels: bug, documentation

#136 Fix typo in caption (explicit --> implicit)
  docs/intro.rst
Labels: bug, documentation

#137 Fix formatting for math formula of DisjointBitSets class method
  dwave/optimization/symbols.pyx
Labels: bug, documentation

#138 Fix two bugs in advanced indexing propagation for non-const non-dynamic arrays with dynamic indexers
  dwave/optimization/src/nodes/indexing.cpp
  releasenotes/notes/fix-bugs-in-advanced-indexing-non-const-array-with-dynamic-indexers-1ef4c31adebcc081.yaml
  tests/cpp/tests/test_nodes_indexing.cpp
Labels: bug

#140 Update `UnaryOpNode` to correctly handle dynamic predecessors
  dwave/optimization/include/dwave-optimization/nodes/mathematical.hpp
  dwave/optimization/src/nodes/_state.hpp
  dwave/optimization/src/nodes/mathematical.cpp
  dwave/optimization/src/nodes/testing.cpp
  releasenotes/notes/UnaryOpNode-dynamic-predecessor-f7cd282afb15270d.yaml
  tests/cpp/tests/test_nodes_mathematical.cpp
Labels: bug

#141 Add missing cases for NaryOpNode min/max/integral
  dwave/optimization/src/nodes/mathematical.cpp
  releasenotes/notes/fix-NaryOpNode-min-max-integral-f42605a5bb2ec1ac.yaml
  tests/cpp/tests/test_nodes_mathematical.cpp
Labels: bug

#142 Note maximum state size at construction
  dwave/optimization/model.pyx
Labels: documentation

#143 Split up some large `.hpp`/`.cpp` files
  dwave/optimization/include/dwave-optimization/nodes.hpp
  dwave/optimization/include/dwave-optimization/nodes/indexing.hpp
  dwave/optimization/include/dwave-optimization/nodes/manipulation.hpp
  dwave/optimization/libcpp/nodes.pxd
  dwave/optimization/src/nodes/indexing.cpp
  dwave/optimization/src/nodes/manipulation.cpp
  meson.build
  tests/cpp/meson.build
  tests/cpp/nodes/indexing/test_advanced.cpp
  tests/cpp/nodes/indexing/test_basic.cpp
  tests/cpp/nodes/mathematical/test_binaryop.cpp
  tests/cpp/nodes/mathematical/test_naryop.cpp
  tests/cpp/nodes/mathematical/test_reduce.cpp
  tests/cpp/nodes/mathematical/test_unaryop.cpp
  tests/cpp/nodes/test_collections.cpp
  tests/cpp/nodes/test_constants.cpp
  tests/cpp/nodes/test_flow.cpp
  tests/cpp/nodes/test_manipulation.cpp
  tests/cpp/nodes/test_numbers.cpp
  tests/cpp/nodes/test_quadratic_model.cpp
  tests/cpp/test_array.cpp
  tests/cpp/test_examples.cpp
  tests/cpp/test_graph.cpp
  tests/cpp/test_utils.cpp
  tests/cpp/tests/test_nodes_mathematical.cpp
  tests/cpp/utils.hpp
Labels: enhancement

#146 Fix the type information for `ArraySymbol.__abs__()`
  dwave/optimization/model.pyi
  releasenotes/notes/math-builtins-812bdc0b3ddc814b.yaml
  tests/test_symbols.py
Labels: bug

#149 Add `Any` symbol
  docs/reference/symbols.rst
  dwave/optimization/include/dwave-optimization/nodes/mathematical.hpp
  dwave/optimization/libcpp/nodes.pxd
  dwave/optimization/model.pyi
  dwave/optimization/model.pyx
  dwave/optimization/src/nodes/mathematical.cpp
  dwave/optimization/symbols.pyi
  dwave/optimization/symbols.pyx
  releasenotes/notes/any-symbol-4c6fdcd16a56e0aa.yaml
  tests/cpp/nodes/mathematical/test_reduce.cpp
  tests/test_symbols.py
Labels: enhancement

#147 Changed formulation of JSSP
  dwave/optimization/generators.py
  releasenotes/notes/change-job-shop-scheduling-generator-f47e34d5a03deb6e.yaml
  tests/test_generators.py
Labels: enhancement

#151 Add logical xor node/symbol
  docs/reference/math.rst
  dwave/optimization/include/dwave-optimization/nodes/mathematical.hpp
  dwave/optimization/libcpp/nodes.pxd
  dwave/optimization/mathematical.py
  dwave/optimization/src/nodes/mathematical.cpp
  dwave/optimization/symbols.pyi
  dwave/optimization/symbols.pyx
  releasenotes/notes/add_logical_xor-82859bd2267d4d2c.yaml
  tests/cpp/nodes/mathematical/test_binaryop.cpp
  tests/test_symbols.py
Labels: enhancement

#154 Test C++ code with gcc11-14
  .circleci/config.yml
Labels: enhancement

#155 Refactor C++ `ArrayIterator` for performance and safety
  dwave/optimization/include/dwave-optimization/array.hpp
  releasenotes/notes/fix-ArrayIterator-9eb71f75a968f570.yaml
  tests/cpp/test_array.cpp
Labels: bug, enhancement
