Repository dwavesystems/dwave-optimization, pull requests merged in 2024-08, with the labels that each got.

#78 Add `Where` symbol
  docs/reference/math.rst
  dwave/optimization/include/dwave-optimization/array.hpp
  dwave/optimization/include/dwave-optimization/graph.hpp
  dwave/optimization/include/dwave-optimization/nodes/flow.hpp
  dwave/optimization/libcpp/nodes.pxd
  dwave/optimization/mathematical.py
  dwave/optimization/src/graph.cpp
  dwave/optimization/src/nodes/flow.cpp
  dwave/optimization/src/nodes/testing.cpp
  dwave/optimization/symbols.pyi
  dwave/optimization/symbols.pyx
  releasenotes/notes/where-node-3d6519b7d78ecb03.yaml
  tests/cpp/tests/test_flow.cpp
  tests/test_symbols.py
Labels: enhancement

#83 Implement `Logical` and `Not` symbols
  docs/reference/math.rst
  dwave/optimization/include/dwave-optimization/nodes/mathematical.hpp
  dwave/optimization/libcpp/nodes.pxd
  dwave/optimization/mathematical.py
  dwave/optimization/src/nodes/mathematical.cpp
  dwave/optimization/symbols.pyi
  dwave/optimization/symbols.pyx
  releasenotes/notes/unary-nodes-refresh-e60c3850212ee7d6.yaml
  tests/cpp/tests/test_nodes_mathematical.cpp
  tests/test_symbols.py
Labels: enhancement

#87 Use CPPFLAGS rather than CFLAGS in CI
  .circleci/config.yml
  dwave/optimization/include/dwave-optimization/nodes/numbers.hpp
  dwave/optimization/src/nodes/testing.cpp
  pyproject.toml
  requirements.txt
Labels: bug

#88 Fix `Array::min()`
  dwave/optimization/include/dwave-optimization/array.hpp
  releasenotes/notes/fix-array-min-ee4c2b1010a21162.yaml
  tests/cpp/tests/test_array.cpp
Labels: bug

#50 Add `Size` symbol
  dwave/optimization/include/dwave-optimization/nodes/indexing.hpp
  dwave/optimization/libcpp/nodes.pxd
  dwave/optimization/model.pyi
  dwave/optimization/model.pyx
  dwave/optimization/src/nodes/indexing.cpp
  dwave/optimization/symbols.pyi
  dwave/optimization/symbols.pyx
  releasenotes/notes/feature-Len-328f804a0f28ba37.yaml
  tests/cpp/tests/test_nodes_indexing.cpp
  tests/test_symbols.py
Labels: enhancement

#93 Bin packing generator
  dwave/optimization/generators.py
  releasenotes/notes/add-bin_packing-generator-510a5af519a964a6.yaml
  tests/test_generators.py
Labels: enhancement

#95 Add `::operands()` method to mathematical nodes
  dwave/optimization/include/dwave-optimization/nodes/mathematical.hpp
  dwave/optimization/src/nodes/mathematical.cpp
  releasenotes/notes/mathematical-nodes-operands-method-918982061ff5af2f.yaml
  tests/cpp/tests/test_nodes_mathematical.cpp
Labels: enhancement

#90 Build with meson
  .circleci/config.yml
  README.rst
  dwave/optimization/_build/_version.py
  meson.build
  pyproject.toml
  releasenotes/notes/meson-8f0d8acf90eb8a34.yaml
  requirements.txt
  setup.cfg
  setup.py
Labels: enhancement

#96 Add helper class for node states
  dwave/optimization/src/nodes/_state.hpp
  dwave/optimization/src/nodes/flow.cpp
  dwave/optimization/src/nodes/indexing.cpp
  dwave/optimization/src/nodes/mathematical.cpp
  dwave/optimization/src/nodes/numbers.cpp
Labels: enhancement

#99 Use default linux arm machine in CircleCI
  .circleci/config.yml
Labels: bug

#98 Fix egregious typo in the README
  README.rst
Labels: bug, documentation

#97 Support scalar broadcasting for binary operations
  dwave/optimization/include/dwave-optimization/nodes/mathematical.hpp
  dwave/optimization/include/dwave-optimization/nodes/numbers.hpp
  dwave/optimization/src/nodes/_state.hpp
  dwave/optimization/src/nodes/flow.cpp
  dwave/optimization/src/nodes/mathematical.cpp
  releasenotes/notes/binary-op-scalar-broadcasting-b7b3d1906da45dea.yaml
  tests/cpp/tests/test_nodes_mathematical.cpp
  tests/test_symbols.py
Labels: enhancement

#102 Add missing include to dwave-optimization/nodes.hpp
  dwave/optimization/include/dwave-optimization/nodes.hpp
Labels: bug
