Repository dwavesystems/dwave-optimization, pull requests merged in 2025-05, with the labels that each got.

#276 Make ScalarOutputMixinStateData available to all classes that inherit from ScalarOutputMixin
  dwave/optimization/include/dwave-optimization/array.hpp
Labels: enhancement

#283 Feature/exp node
  dwave/optimization/include/dwave-optimization/nodes/mathematical.hpp
  dwave/optimization/libcpp/nodes.pxd
  dwave/optimization/mathematical.py
  dwave/optimization/src/nodes/mathematical.cpp
  dwave/optimization/symbols.pyi
  dwave/optimization/symbols.pyx
  releasenotes/notes/add-exp-node-b9c3a41c179d8d54.yaml
  tests/cpp/nodes/mathematical/test_unaryop.cpp
  tests/test_symbols.py
Labels: enhancement

#285 Add absolute function
  dwave/optimization/mathematical.py
  dwave/optimization/symbols.pyx
  releasenotes/notes/feature-absolute-716cc20fc7a5d725.yaml
  tests/test_symbols.py
Labels: documentation, enhancement

#279 Move the utility functions out of symbols.pyx
  dwave/optimization/_model.pxd
  dwave/optimization/_model.pyx
  dwave/optimization/_utilities.pxd
  dwave/optimization/_utilities.pyx
  dwave/optimization/libcpp/__init__.pxd
  dwave/optimization/symbols.pyx
  meson.build
Labels: enhancement

#284 Build with Cython 3.1
  dwave/optimization/_utilities.pxd
  dwave/optimization/_utilities.pyx
  dwave/optimization/libcpp/__init__.pxd
  dwave/optimization/libcpp/array.pxd
  dwave/optimization/libcpp/graph.pxd
  dwave/optimization/libcpp/nodes.pxd
  dwave/optimization/symbols.pyx
  pyproject.toml
  requirements.txt
Labels: enhancement

#289 Fix iteration over `ArraySymbols`
  dwave/optimization/_model.pyi
  dwave/optimization/_model.pyx
  releasenotes/notes/fix-ArraySymbol-iteration-dfc7618815166c98.yaml
  tests/test_model.py
Labels: bug

#291 Update mathematical nodes to hold their op
  dwave/optimization/include/dwave-optimization/nodes/mathematical.hpp
  dwave/optimization/src/nodes/mathematical.cpp
Labels: enhancement

#288 Remove symbol construction boilerplate from many symbols
  dwave/optimization/_model.pyx
  dwave/optimization/symbols.pyx
Labels: enhancement

#292 Add `SafeDivide` symbol
  dwave/optimization/include/dwave-optimization/nodes/mathematical.hpp
  dwave/optimization/libcpp/nodes.pxd
  dwave/optimization/mathematical.py
  dwave/optimization/src/nodes/mathematical.cpp
  dwave/optimization/symbols.pyx
  releasenotes/notes/feature-safe-divide-e49a7c268c4f4de9.yaml
  tests/cpp/nodes/mathematical/test_binaryop.cpp
  tests/test_symbols.py
Labels: enhancement
