Repository dwavesystems/dwave-optimization, pull requests merged in 2025-02, with the labels that each got.

#222 Implement `axis` kwarg for `ArraySymbol.prod()`
  dwave/optimization/_model.pyx
  dwave/optimization/include/dwave-optimization/nodes/mathematical.hpp
  dwave/optimization/include/dwave-optimization/nodes/numbers.hpp
  dwave/optimization/libcpp/nodes.pxd
  dwave/optimization/src/nodes/mathematical.cpp
  dwave/optimization/src/nodes/numbers.cpp
  dwave/optimization/symbols.pyx
  releasenotes/notes/PartialProd-fbc3c145701acf2d.yaml
  tests/cpp/nodes/mathematical/test_reduce.cpp
  tests/test_symbols.py
Labels: enhancement

#226 Add a meson build option to enable/disable/auto tests
  meson.build
  meson.options
Labels: enhancement

#224 Use catch2 v3.8.0 for C++ testing
  subprojects/catch2.wrap
  tests/cpp/nodes/indexing/test_advanced.cpp
  tests/cpp/nodes/indexing/test_basic.cpp
  tests/cpp/nodes/mathematical/test_binaryop.cpp
  tests/cpp/nodes/mathematical/test_reduce.cpp
  tests/cpp/nodes/mathematical/test_unaryop.cpp
  tests/cpp/nodes/test_collections.cpp
  tests/cpp/nodes/test_constants.cpp
  tests/cpp/nodes/test_flow.cpp
  tests/cpp/nodes/test_manipulation.cpp
  tests/cpp/nodes/test_numbers.cpp
  tests/cpp/nodes/test_quadratic_model.cpp
  tests/cpp/test_array.cpp
  tests/cpp/test_utils.cpp
Labels: enhancement

#225 Improve the runtime of C++ tests
  tests/cpp/test_utils.cpp
Labels: enhancement

#228 Improve the documentation of `Model.state_size()` and similar methods
  dwave/optimization/_model.pyx
Labels: documentation

#229 Add `Array::minmax()` method
  dwave/optimization/include/dwave-optimization/array.hpp
  dwave/optimization/include/dwave-optimization/nodes/collections.hpp
  dwave/optimization/include/dwave-optimization/nodes/constants.hpp
  dwave/optimization/include/dwave-optimization/nodes/flow.hpp
  dwave/optimization/include/dwave-optimization/nodes/indexing.hpp
  dwave/optimization/include/dwave-optimization/nodes/manipulation.hpp
  dwave/optimization/include/dwave-optimization/nodes/mathematical.hpp
  dwave/optimization/include/dwave-optimization/nodes/numbers.hpp
  dwave/optimization/include/dwave-optimization/nodes/testing.hpp
  dwave/optimization/src/array.cpp
  dwave/optimization/src/nodes/collections.cpp
  dwave/optimization/src/nodes/constants.cpp
  dwave/optimization/src/nodes/flow.cpp
  dwave/optimization/src/nodes/indexing.cpp
  dwave/optimization/src/nodes/manipulation.cpp
  dwave/optimization/src/nodes/mathematical.cpp
  dwave/optimization/src/nodes/numbers.cpp
  dwave/optimization/src/nodes/testing.cpp
  releasenotes/notes/Array.minmax-6de0b413d2c77b4c.yaml
  tests/cpp/nodes/mathematical/test_binaryop.cpp
  tests/cpp/nodes/mathematical/test_naryop.cpp
  tests/cpp/nodes/mathematical/test_reduce.cpp
  tests/cpp/nodes/mathematical/test_unaryop.cpp
Labels: bug, enhancement

#231 Fix missing colon
  dwave/optimization/_model.pyx
Labels: bug, documentation

#230 Flatten Symbol and ArraySymbol docs
  docs/reference/symbols.rst
  dwave/optimization/_model.pyx
Labels: documentation

#233 Move symbol unit tests to separate file
  tests/test_symbols.py
  tests/utils.py
Labels: enhancement

#234 Add Expit symbol
  dwave/optimization/include/dwave-optimization/nodes/mathematical.hpp
  dwave/optimization/libcpp/nodes.pxd
  dwave/optimization/mathematical.py
  dwave/optimization/src/nodes/mathematical.cpp
  dwave/optimization/symbols.pyi
  dwave/optimization/symbols.pyx
  releasenotes/notes/add-expit-node-b9f4c62ca9136a86.yaml
  tests/cpp/nodes/mathematical/test_unaryop.cpp
  tests/test_symbols.py
Labels: enhancement

#232 Add `ARange` symbol and support for slicing by integers
  dwave/optimization/include/dwave-optimization/nodes.hpp
  dwave/optimization/include/dwave-optimization/nodes/creation.hpp
  dwave/optimization/libcpp/nodes.pxd
  dwave/optimization/mathematical.py
  dwave/optimization/src/array.cpp
  dwave/optimization/src/nodes/_state.hpp
  dwave/optimization/src/nodes/creation.cpp
  dwave/optimization/symbols.pyx
  meson.build
  releasenotes/notes/feature-ARangeNode-590a21d82557fa46.yaml
  tests/cpp/meson.build
  tests/cpp/nodes/test_creation.cpp
  tests/test_symbols.py
Labels: enhancement

#235 Tidy serialization code and tests
  dwave/optimization/_model.pyi
  dwave/optimization/_model.pyx
  dwave/optimization/model.py
  dwave/optimization/states.pyi
  dwave/optimization/states.pyx
  tests/test_model.py
  tests/test_states.py
Labels: enhancement

#236 Remove some erroneous asserts
  dwave/optimization/src/nodes/mathematical.cpp
  tests/cpp/nodes/mathematical/test_binaryop.cpp
Labels: bug

#237 Fix ConcatenateNode propagation
  dwave/optimization/src/nodes/manipulation.cpp
  releasenotes/notes/fix-ConcatenateNode-updates-f5eef8f7efda3879.yaml
  tests/cpp/nodes/test_manipulation.cpp
Labels: bug

#239 Fix ConcatenateNode::minmax()
  dwave/optimization/src/nodes/manipulation.cpp
  releasenotes/notes/fix-concatenate-minmax-cache-4a9fe2418b6ab432.yaml
  tests/cpp/nodes/test_manipulation.cpp
Labels: bug

#242 Fix bug in basic indexing propagation
  dwave/optimization/src/nodes/indexing.cpp
  releasenotes/notes/fix-basic-indexing-static-size-or-simple-domain-propagation-442b3563091f54f7.yaml
  tests/cpp/nodes/indexing/test_basic.cpp
Labels: bug

#244 Feature/log node
  dwave/optimization/include/dwave-optimization/nodes/mathematical.hpp
  dwave/optimization/libcpp/nodes.pxd
  dwave/optimization/mathematical.py
  dwave/optimization/src/nodes/mathematical.cpp
  dwave/optimization/symbols.pyi
  dwave/optimization/symbols.pyx
  releasenotes/notes/add-log-node-f7c505316b23a787.yaml
  tests/cpp/nodes/mathematical/test_unaryop.cpp
  tests/test_symbols.py
Labels: enhancement

#245 Correctly update the state of the mask when reverting a PutNode
  dwave/optimization/src/nodes/manipulation.cpp
  releasenotes/notes/fix-PutNode-revert-9dd0507853851bae.yaml
  tests/cpp/nodes/test_manipulation.cpp
Labels: bug
