Repository dwavesystems/dwave-optimization, pull requests merged in 2025-07, with the labels that each got.

#318 Add type_list C++ utility class
  dwave/optimization/include/dwave-optimization/type_list.hpp
  releasenotes/notes/feature-type_list-f59517a4da17d659.yaml
  tests/cpp/meson.build
  tests/cpp/test_type_list.cpp
Labels: enhancement

#334 Move iterators into a separate header file
  dwave/optimization/include/dwave-optimization/array.hpp
  dwave/optimization/include/dwave-optimization/iterators.hpp
  dwave/optimization/include/dwave-optimization/typing.hpp
  tests/cpp/meson.build
  tests/cpp/test_array.cpp
  tests/cpp/test_iterators.cpp
Labels: enhancement

#333 Use std::ranges::view_interface for Array::View
  dwave/optimization/include/dwave-optimization/array.hpp
  dwave/optimization/src/array.cpp
  dwave/optimization/src/nodes/mathematical.cpp
  dwave/optimization/src/nodes/testing.cpp
  releasenotes/notes/view-interface-263c01dc2e6ae1b5.yaml
  tests/cpp/test_array.cpp
Labels: enhancement

#336 Add minimal docs for dynamic array symbols
  docs/philosophy.rst
  dwave/optimization/_model.pyx
Labels: documentation, enhancement

#340 Constant interning at Python level
  dwave/optimization/model.py
  tests/test_generators.py
  tests/test_model.py
  tests/test_symbols.py
Labels: enhancement

#342 Enable constant promotion on arithmetic dunder methods
  dwave/optimization/_model.pyx
  dwave/optimization/symbols.pyx
  releasenotes/notes/constant-promotion-9bc974cd760c83e0.yaml
  tests/test_model.py
  tests/test_symbols.py
Labels: enhancement

#166 Add AccumulateZip node/symbol
  docs/models.rst
  dwave/optimization/__init__.py
  dwave/optimization/_model.pxd
  dwave/optimization/_model.pyx
  dwave/optimization/expression.py
  dwave/optimization/include/dwave-optimization/array.hpp
  dwave/optimization/include/dwave-optimization/nodes.hpp
  dwave/optimization/include/dwave-optimization/nodes/inputs.hpp
  dwave/optimization/include/dwave-optimization/nodes/lambda.hpp
  dwave/optimization/libcpp/graph.pxd
  dwave/optimization/libcpp/nodes.pxd
  dwave/optimization/model.py
  dwave/optimization/src/array.cpp
  dwave/optimization/src/nodes/lambda.cpp
  dwave/optimization/symbols.pyi
  dwave/optimization/symbols.pyx
  meson.build
  releasenotes/notes/add-expression-and-accumulate-zip-eb2c7f6feb4f2d0f.yaml
  tests/cpp/meson.build
  tests/cpp/nodes/test_lambda.cpp
  tests/test_expression.py
  tests/test_symbols.py
Labels: enhancement

#354 Add `deduplicate_diff_view()` view for use in loops
  dwave/optimization/include/dwave-optimization/array.hpp
  dwave/optimization/include/dwave-optimization/utils.hpp
  dwave/optimization/src/array.cpp
  dwave/optimization/src/utils.cpp
  releasenotes/notes/feature-deduplicate_diff_view-ec59714a2eab1ec4.yaml
  tests/cpp/test_array.cpp
  tests/cpp/test_utils.cpp
Labels: enhancement

#357 Add Resize symbol
  dwave/optimization/_model.pyi
  dwave/optimization/_model.pyx
  dwave/optimization/include/dwave-optimization/nodes/manipulation.hpp
  dwave/optimization/libcpp/nodes.pxd
  dwave/optimization/mathematical.py
  dwave/optimization/src/nodes/manipulation.cpp
  dwave/optimization/symbols.pyi
  dwave/optimization/symbols.pyx
  releasenotes/notes/feature-Resize-ac0f14927d292c90.yaml
  tests/cpp/nodes/test_manipulation.cpp
  tests/test_symbols.py
Labels: enhancement

#358 Fix warnings thrown when building the docs for AccumulateZip
  dwave/optimization/symbols.pyx
Labels: bug, documentation

#339 Add MeanNode/Symbol
  dwave/optimization/include/dwave-optimization/nodes/statistics.hpp
  dwave/optimization/libcpp/nodes.pxd
  dwave/optimization/mathematical.py
  dwave/optimization/src/nodes/statistics.cpp
  dwave/optimization/symbols.pyx
  meson.build
  releasenotes/notes/mean-symbol-932d07bdd51f738b.yaml
  tests/cpp/meson.build
  tests/cpp/nodes/test_statistics.cpp
  tests/test_symbols.py
Labels: enhancement
