Repository dwavesystems/dwave-optimization, pull requests merged in 2025-06, with the labels that each got.

#307 Support two dynamic predecessors for BinaryOp
  dwave/optimization/src/nodes/mathematical.cpp
  releasenotes/notes/binaryopnode-support-both-predecessors-dynamic-096fc6daa7c0fe0b.yaml
  tests/cpp/nodes/mathematical/test_binaryop.cpp
Labels: enhancement

#301 Check buffer flags in `Constant` and `StateView`
  dwave/optimization/states.pyx
  dwave/optimization/symbols.pyx
  releasenotes/notes/fix-buffer-flags-64c25648123d5c90.yaml
  tests/test_states.py
  tests/test_symbols.py
Labels: bug

#310 Move AdvancedIndexingNode's shape to node state data
  dwave/optimization/include/dwave-optimization/nodes/indexing.hpp
  dwave/optimization/src/nodes/indexing.cpp
  releasenotes/notes/fix-adv-indexing-dynamic-shape-8ad943e35d22cccd.yaml
Labels: bug

#314 Fix spelling principals -> principles
  docs/index.rst
  docs/philosophy.rst
  dwave/optimization/_model.pyx
Labels: bug, documentation

#320 Support all dynamic predecessors in WhereNode
  dwave/optimization/include/dwave-optimization/nodes/flow.hpp
  dwave/optimization/src/nodes/_state.hpp
  dwave/optimization/src/nodes/flow.cpp
  releasenotes/notes/where-node-support-all-dynamic-predecessors-ae73f2f65d8a00a6.yaml
  tests/cpp/nodes/test_flow.cpp
Labels: enhancement

#325 Make ArrayStateData buffer/updates private
  dwave/optimization/include/dwave-optimization/array.hpp
  dwave/optimization/src/nodes/_state.hpp
  dwave/optimization/src/nodes/creation.cpp
  dwave/optimization/src/nodes/flow.cpp
  dwave/optimization/src/nodes/manipulation.cpp
  dwave/optimization/src/nodes/mathematical.cpp
  tests/cpp/test_array.cpp
Labels: enhancement

#323 Fix expensive resursion in Graph::recursive_reset()
  dwave/optimization/src/graph.cpp
Labels: bug
