Repository dwavesystems/dwave-optimization, pull requests merged in 2025-08, with the labels that each got.

#348 Fix minor typos
  docs/index.rst
  docs/philosophy.rst
  dwave/optimization/generators.py
Labels: documentation

#363 Fix ArgSortNode::revert
  dwave/optimization/src/nodes/sorting.cpp
  tests/cpp/nodes/test_sorting.cpp
Labels: bug

#370 Fix SetNode::assign() method
  dwave/optimization/src/nodes/collections.cpp
  releasenotes/notes/fix-SetNode-assign-c81fb9adbb74957d.yaml
  tests/cpp/nodes/test_collections.cpp
Labels: bug

#359 Add SoftMaxNode/Symbol
  dwave/optimization/include/dwave-optimization/nodes/mathematical.hpp
  dwave/optimization/libcpp/nodes.pxd
  dwave/optimization/mathematical.py
  dwave/optimization/src/nodes/mathematical.cpp
  dwave/optimization/symbols.pyx
  releasenotes/notes/softmax-symbol-f6508ce3032120f9.yaml
  tests/cpp/meson.build
  tests/cpp/nodes/mathematical/test_softmax.cpp
  tests/test_symbols.py
Labels: enhancement

#371 Add broadcasting support
  dwave/optimization/include/dwave-optimization/nodes/manipulation.hpp
  dwave/optimization/libcpp/nodes.pxd
  dwave/optimization/mathematical.py
  dwave/optimization/src/nodes/manipulation.cpp
  dwave/optimization/symbols.pyx
  releasenotes/notes/feature-broadcasting-773034ff391baf44.yaml
  tests/cpp/nodes/test_manipulation.cpp
  tests/test_mathematical.py
  tests/test_symbols.py
Labels: enhancement

#374 Generate fewer C++ CI tests
  .circleci/config.yml
Labels: enhancement
