Repository dwavesystems/dwave-optimization, pull requests merged in 2025-01, with the labels that each got.

#189 Mark Decision::update() and ConstantNode::update() as noreturn
  dwave/optimization/include/dwave-optimization/graph.hpp
  dwave/optimization/include/dwave-optimization/nodes/collections.hpp
  dwave/optimization/include/dwave-optimization/nodes/constants.hpp
  dwave/optimization/src/graph.cpp
  dwave/optimization/src/nodes/constants.cpp
Labels: enhancement

#186 Refactor some tests to use ArrayValidationNode
  tests/cpp/nodes/indexing/test_advanced.cpp
  tests/cpp/nodes/indexing/test_basic.cpp
  tests/cpp/nodes/test_collections.cpp
  tests/cpp/utils.hpp
Labels: enhancement

#194 Fix for issue 190
  dwave/optimization/mathematical.py
  tests/test_symbols.py
Labels: bug

#195 Remove `Decision::default_move()` method
  dwave/optimization/include/dwave-optimization/graph.hpp
  dwave/optimization/include/dwave-optimization/nodes/collections.hpp
  dwave/optimization/include/dwave-optimization/nodes/numbers.hpp
  dwave/optimization/include/dwave-optimization/nodes/testing.hpp
  dwave/optimization/src/nodes/collections.cpp
  dwave/optimization/src/nodes/numbers.cpp
  dwave/optimization/src/nodes/testing.cpp
  releasenotes/notes/remove-default-move-9bfb3616a0bdeffb.yaml
  tests/cpp/meson.build
  tests/cpp/nodes/indexing/test_basic.cpp
  tests/cpp/nodes/test_collections.cpp
  tests/cpp/nodes/test_manipulation.cpp
  tests/cpp/nodes/test_numbers.cpp
  tests/cpp/test_examples.cpp
  tests/cpp/test_graph.cpp
Labels: enhancement

#197 Build C++ docs, but do not include them in any toctrees
  .circleci/config.yml
  docs/Doxyfile
  docs/Makefile
  docs/conf.py
  docs/reference/cpp.rst
  docs/requirements.txt
Labels: documentation, enhancement

#198 Add release notes to docs
  docs/conf.py
  docs/index.rst
  docs/release_notes.rst
  docs/requirements.txt
  requirements.txt
Labels: documentation, enhancement

#203 Add very basic documentation for C++ Array class
  docs/Doxyfile
  dwave/optimization/include/dwave-optimization/array.hpp
Labels: documentation, enhancement

#205 Fix stack() example formatting
  dwave/optimization/mathematical.py
Labels: bug, documentation

#206 Minor fixes
  dwave/optimization/mathematical.py
  dwave/optimization/symbols.pyi
  dwave/optimization/symbols.pyx
  releasenotes/notes/fix-symbols-import-96d850c767eab38c.yaml
  tests/test_symbols.py
Labels: bug

#207 Format all C++ files with clang-format
  dwave/optimization/include/dwave-optimization/array.hpp
  dwave/optimization/include/dwave-optimization/graph.hpp
  dwave/optimization/include/dwave-optimization/nodes/constants.hpp
  dwave/optimization/include/dwave-optimization/nodes/manipulation.hpp
  dwave/optimization/include/dwave-optimization/nodes/mathematical.hpp
  dwave/optimization/include/dwave-optimization/nodes/numbers.hpp
  dwave/optimization/include/dwave-optimization/nodes/testing.hpp
  dwave/optimization/src/array.cpp
  dwave/optimization/src/graph.cpp
  dwave/optimization/src/nodes/manipulation.cpp
  dwave/optimization/src/nodes/mathematical.cpp
  dwave/optimization/src/nodes/quadratic_model.cpp
  tests/cpp/nodes/mathematical/test_binaryop.cpp
  tests/cpp/nodes/mathematical/test_naryop.cpp
  tests/cpp/nodes/mathematical/test_reduce.cpp
  tests/cpp/nodes/mathematical/test_unaryop.cpp
  tests/cpp/nodes/test_manipulation.cpp
  tests/cpp/test_array.cpp
  tests/cpp/test_graph.cpp
  tests/cpp/test_utils.cpp
Labels: enhancement

#201 Add ability to insert values into an array symbol
  dwave/optimization/include/dwave-optimization/nodes/constants.hpp
  dwave/optimization/include/dwave-optimization/nodes/manipulation.hpp
  dwave/optimization/libcpp/nodes.pxd
  dwave/optimization/mathematical.py
  dwave/optimization/src/nodes/_state.hpp
  dwave/optimization/src/nodes/manipulation.cpp
  dwave/optimization/symbols.pyx
  releasenotes/notes/feature-Put-f07f543015dd2ed8.yaml
  tests/cpp/nodes/test_manipulation.cpp
  tests/test_symbols.py
Labels: enhancement

#210 Add `Rint` symbol
  dwave/optimization/include/dwave-optimization/nodes/mathematical.hpp
  dwave/optimization/libcpp/nodes.pxd
  dwave/optimization/mathematical.py
  dwave/optimization/src/nodes/mathematical.cpp
  dwave/optimization/symbols.pyi
  dwave/optimization/symbols.pyx
  releasenotes/notes/add-rint-node-3d000c89d8dc4236.yaml
  tests/cpp/nodes/mathematical/test_unaryop.cpp
  tests/test_symbols.py
Labels: enhancement

#212 Fix `sqrt()` example formatting
  dwave/optimization/symbols.pyx
Labels: bug, documentation

#215 Disallow non-finite values for `Constant` symbol
  dwave/optimization/symbols.pyx
  releasenotes/notes/disallow-nonfinite-values-in-constant-f25849a817c6d28d.yaml
  tests/test_symbols.py
Labels: bug, enhancement

#218 Improve QOL when reshaping array symbols
  docs/reference/symbols.rst
  dwave/optimization/_model.pyi
  dwave/optimization/_model.pyx
  dwave/optimization/include/dwave-optimization/array.hpp
  dwave/optimization/include/dwave-optimization/nodes/manipulation.hpp
  dwave/optimization/libcpp/array.pxd
  dwave/optimization/libcpp/nodes.pxd
  dwave/optimization/src/nodes/_state.hpp
  dwave/optimization/src/nodes/manipulation.cpp
  dwave/optimization/symbols.pyi
  dwave/optimization/symbols.pyx
  releasenotes/notes/feature-ArraySymbol-flatten-a499f7edf2e28185.yaml
  tests/cpp/nodes/test_manipulation.cpp
  tests/test_symbols.py
Labels: bug, enhancement
